spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  mongodb:
    embedded:
      version: 4.0.2
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.emax-it.com/auth/realms/spring-security-training
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-security-training-client
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.security: INFO